# Generated by Django 5.2.6 on 2025-09-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=50)),
                ('crop_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('market_price_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketPrice.crop')),
            ],
        ),
    ]
